on:
  push:
  schedule:
    - cron:  '15 * * * *' # Every hour at minute 15. Ref https://crontab.guru/examples.html
name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Scrape
      run: npm run scrape
      # env:
      #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
    - name: Build
      run: npm run build
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      run: npm run deploy
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
